# Generated by Django 5.1.1 on 2024-09-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_remove_documents_file_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="status",
            field=models.CharField(blank=True, default="pending", max_length=8),
        ),
    ]
