# Generated by Django 5.1.1 on 2024-09-10 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_admin", "0002_alter_departments_id"),
        ("custom_auth", "0002_alter_users_department"),
        ("hod", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modules",
            old_name="uploaded_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="modules",
            name="file_name",
        ),
        migrations.RemoveField(
            model_name="modules",
            name="file_path",
        ),
        migrations.RemoveField(
            model_name="modules",
            name="user_id",
        ),
        migrations.AddField(
            model_name="modules",
            name="deparment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="custom_admin.departments",
            ),
        ),
        migrations.AddField(
            model_name="modules",
            name="learning_hours",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="modules",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="custom_auth.teachers",
            ),
        ),
        migrations.DeleteModel(
            name="Subjects",
        ),
    ]
