# Generated by Django 5.1.1 on 2024-09-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hod", "0005_modules_program"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modules",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
