# Generated by Django 5.1.1 on 2024-09-10 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("custom_admin", "0001_initial"),
        ("custom_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modules",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField()),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="custom_auth.teachers",
                    ),
                ),
            ],
            options={
                "db_table": "modules",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Subjects",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("subject_name", models.CharField(max_length=255)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="custom_admin.departments",
                    ),
                ),
            ],
            options={
                "db_table": "subjects",
                "managed": True,
            },
        ),
    ]
