# Generated by Django 5.1.1 on 2024-09-17 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_admin", "0005_rename_options_programs"),
        ("hod", "0004_modules_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="modules",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="custom_admin.programs",
            ),
        ),
    ]
