# Generated by Django 5.1.1 on 2024-09-10 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_admin", "0003_remove_classes_department_options"),
        ("custom_auth", "0002_alter_users_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="s_class",
        ),
        migrations.RemoveField(
            model_name="teachers",
            name="department",
        ),
        migrations.AddField(
            model_name="students",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="custom_admin.options",
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="Hods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
