# Generated by Django 5.1.1 on 2024-09-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "custom_auth",
            "0003_remove_students_s_class_remove_teachers_department_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
    ]
