# Generated by Django 5.1.1 on 2024-09-13 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0005_passwordresets_expired_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresets",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 13, 11, 48, 33, 507762)
            ),
        ),
    ]
