# Generated by Django 5.1.1 on 2024-09-14 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0010_alter_passwordresets_expired_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresets",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 14, 20, 51, 18, 383521, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
