# Generated by Django 5.1.1 on 2024-09-17 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0013_alter_passwordresets_expired_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="students",
            old_name="option",
            new_name="program",
        ),
        migrations.AlterField(
            model_name="passwordresets",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 17, 11, 13, 3, 288641, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
