# Generated by Django 5.1.1 on 2024-09-13 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0004_users_is_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresets",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 13, 11, 37, 1, 787435)
            ),
        ),
        migrations.AlterField(
            model_name="passwordresets",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
