# Generated by Django 5.1.1 on 2024-09-13 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0006_alter_passwordresets_expired_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresets",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 13, 10, 53, 19, 981810, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
