# Generated by Django 5.1.1 on 2024-09-17 10:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_admin", "0005_rename_options_programs"),
        ("custom_auth", "0014_rename_option_students_program_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresets",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 17, 11, 38, 20, 92206, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="custom_admin.programs",
            ),
        ),
    ]
