# Generated by Django 5.1.1 on 2024-09-17 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0015_alter_passwordresets_expired_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresets",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 17, 17, 28, 52, 510198, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
