# Generated by Django 5.1.1 on 2024-10-03 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0018_alter_passwordresets_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresets',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 3, 9, 42, 46, 145841, tzinfo=datetime.timezone.utc)),
        ),
    ]
