# Generated by Django 5.1.1 on 2024-09-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0002_alter_users_department"),
        ("hod", "0001_initial"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documents",
            name="file_name",
        ),
        migrations.RemoveField(
            model_name="documents",
            name="file_path",
        ),
        migrations.RemoveField(
            model_name="documents",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="documents",
            name="title",
        ),
        migrations.RemoveField(
            model_name="documents",
            name="user_id",
        ),
        migrations.AddField(
            model_name="documents",
            name="file",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="documents",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hod.modules",
            ),
        ),
        migrations.AddField(
            model_name="documents",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="custom_auth.students",
            ),
        ),
        migrations.AlterField(
            model_name="documents",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="documents",
            name="uploaded_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
