# Generated by Django 5.1.1 on 2024-09-14 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0008_alter_passwordresets_expired_at"),
        ("student", "0003_alter_documents_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity", models.CharField(max_length=255)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="custom_auth.students",
                    ),
                ),
            ],
        ),
    ]
