# Generated by Django 5.1.1 on 2024-10-03 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_auth', '0019_alter_passwordresets_expired_at'),
        ('hod', '0006_alter_modules_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=8)),
                ('year', models.CharField(max_length=1)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hod.modules')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='custom_auth.teachers')),
            ],
        ),
    ]
