# Generated by Django 5.1.1 on 2024-09-10 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_admin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departments",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                max_length=64,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
