# Generated by Django 5.1.1 on 2024-09-10 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_admin", "0003_remove_classes_department_options"),
        (
            "custom_auth",
            "0003_remove_students_s_class_remove_teachers_department_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Classes",
        ),
    ]
