# Generated by Django 5.1.1 on 2024-09-17 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_admin", "0004_delete_classes"),
        ("custom_auth", "0014_rename_option_students_program_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Options",
            new_name="Programs",
        ),
    ]
